version: "3.9"
services:
  api:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis
      - db
  worker:
    build: .
    command: python -m app.worker
    env_file:
      - .env
    depends_on:
      - redis
      - db
  redis:
    image: redis:7-alpine
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: transcriber
      POSTGRES_USER: transcriber
      POSTGRES_PASSWORD: transcriber
    ports:
      - "5432:5432"
